# Generated by Django 4.1.6 on 2023-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
